test

diff --git a/.github/workflows/test_status.yaml b/.github/workflows/test_status.yaml
--- a/.github/workflows/test_status.yaml
+++ b/.github/workflows/test_status.yaml
@@ -28,10 +28,10 @@ jobs:
       - name: checkout
         run: echo "Execute checkout"
   
-      - name: Fail the job
-        run: |
-          echo "Something went wrong!"
-          exit 1
+      # - name: Fail the job
+      #   run: |
+      #     echo "Something went wrong!"
+      #     exit 1
 
   
   job3:
